require("plugins_setup")
require("core.settings")
require 'core.colorscheme'
require("plugins.file_explorer_view")
require("core.shortcuts")
require("plugins.show_terminal")
require("plugins.tree_sitter")
require("plugins.lsp_config")
require("plugins.autocmp_config")
require("plugins.devicons")
require("plugins.lualine_config")
require("plugins.autopairs")
require("plugins.dap_config")

require("plugins.rust_config")
